// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkstHtu_1qbpytyB6Rt_jsnFJO2U_Xuo',
    appId: '1:411117759913:android:40181dbada5df7c5ea68b8',
    messagingSenderId: '411117759913',
    projectId: 'unichat2-c79f7',
    storageBucket: 'unichat2-c79f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0XXCIuzMBJKpqI0kYB8YgjAa3u-gAd-Y',
    appId: '1:411117759913:ios:0ddd59f7a92151f0ea68b8',
    messagingSenderId: '411117759913',
    projectId: 'unichat2-c79f7',
    storageBucket: 'unichat2-c79f7.appspot.com',
    iosBundleId: 'com.example.unichatPoojanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0XXCIuzMBJKpqI0kYB8YgjAa3u-gAd-Y',
    appId: '1:411117759913:ios:41b015d690e01232ea68b8',
    messagingSenderId: '411117759913',
    projectId: 'unichat2-c79f7',
    storageBucket: 'unichat2-c79f7.appspot.com',
    iosBundleId: 'com.example.unichatPoojanProject.RunnerTests',
  );
}
