// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC7w11UUkz3lmuoITsOwhrMTIMGUOjfRw',
    appId: '1:730450509070:web:64f484afc80620eb0feb5f',
    messagingSenderId: '730450509070',
    projectId: 'softwareengg-2f798',
    authDomain: 'softwareengg-2f798.firebaseapp.com',
    storageBucket: 'softwareengg-2f798.appspot.com',
    measurementId: 'G-XYD8WHDW5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzS4tQVtFnYu6SQ83eLeVfP5nfP-Gc-tA',
    appId: '1:730450509070:android:7636476d082cbb3e0feb5f',
    messagingSenderId: '730450509070',
    projectId: 'softwareengg-2f798',
    storageBucket: 'softwareengg-2f798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxxTZzHeTzZrfWvxmO37RU3zh6lItyYM',
    appId: '1:730450509070:ios:11a45e0c7ddf69760feb5f',
    messagingSenderId: '730450509070',
    projectId: 'softwareengg-2f798',
    storageBucket: 'softwareengg-2f798.appspot.com',
    iosBundleId: 'com.example.unichatPoojanProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcxxTZzHeTzZrfWvxmO37RU3zh6lItyYM',
    appId: '1:730450509070:ios:dbb75213be469e610feb5f',
    messagingSenderId: '730450509070',
    projectId: 'softwareengg-2f798',
    storageBucket: 'softwareengg-2f798.appspot.com',
    iosBundleId: 'com.example.unichatPoojanProject.RunnerTests',
  );
}
